### ISSUE TITLE
the cursedness is killing me 

### ISSUE THREAD

**Issue by BoogieMonster1O1** [TheCursedFabricProject/cursed-fluid-api#3]
81000 :concern:
just use fractions smh
81000 is too big

**Comment by CoolMineman** [comment]
81000 lets you transfer 113,868,790,578,454 buckets in one long
fractions are scuffed
***B E G O N E***

**Comment by BoogieMonster1O1** [comment]
three ints arr the future

**Comment by BoogieMonster1O1** [comment]
1620 also good and best

**Comment by BoogieMonster1O1** [comment]
also lba uses fractions

**Comment by sschr15** [comment]
> also lba uses fractions

Do we care about non-cursed fluid APIs? I didn't think so

**Comment by CoolMineman** [comment]
![yeet](https://user-images.githubusercontent.com/62723322/100406490-9830e400-302b-11eb-951d-14af04669fa1.png)

**Comment by CoolMineman** [comment]
ding dong your opinion is wrong

**Comment by sschr15** [comment]
Apparently now the superior way to chat is with GitHub issue comments
